In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
#Onehotencoder
from sklearn.preprocessing import OneHotEncoder

In [3]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']

})

df.head()

color
0    red
1   blue
2  green
3  green
4    red

In [5]:
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['color']]).toarray()

In [6]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [7]:
encoder_df.head()

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0

In [ ]:
#for any event
encoder.transform([['blue']]).toarray()

d:\Miniconda3\envs\ml_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [11]:
pd.concat([df,encoder_df],axis=1)

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [16]:
#label encoding

from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

print(df.head())

lbl_encoder.fit_transform(df[['color']])
print("For value red ", lbl_encoder.transform([['red']]))



   color
0    red
1   blue
2  green
3  green
4    red
For value red  [2]


d:\Miniconda3\envs\ml_env\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
d:\Miniconda3\envs\ml_env\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [17]:
#Ordinal Encoding- assigning order

from sklearn.preprocessing import OrdinalEncoder
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})


encoder=OrdinalEncoder(categories=[['small','medium','large']])
encoder.fit_transform(df[['size']])




array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [18]:
encoder.transform([['small']])

d:\Miniconda3\envs\ml_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

In [19]:
#Target guided encoding- we replace each category with numerical value based on median or mean 

df= pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,180,320]
})

In [22]:
print(df.groupby('city')['price'].mean())
mean_price=df.groupby('city')['price'].mean().to_dict()
mean_price


city
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64


{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [24]:
df['city_encoding']=df['city'].map(mean_price)
df.head()


city  price  city_encoding
0  New York    200          190.0
1    London    150          150.0
2     Paris    300          310.0
3     Tokyo    250          250.0
4  New York    180          190.0